data_loader:
  data:
    url: "https://zenodo.org/records/15131565/files/FAIR_Universe_HiggsML_data.zip"
    train_size: 0.35
    processes:
      - htautau
      - ztautau
      - ttbar

  preprocess:
    seed: 42
    selections: >
      DER_mass_transverse_met_lep <= 250.0 and
      DER_mass_vis <= 500.0 and
      DER_sum_pt <= 1000 and
      DER_pt_tot <= 250 and
      DER_deltar_had_lep <= 4.5 and
      DER_pt_h <= 400 and
      DER_pt_ratio_lep_had <= 9.0

  systematics:
    TES_up:
      tes: 1.002
    TES_dn:
      tes: 0.998
    JES_up:
      jes: 1.002
    JES_dn:
      jes: 0.998

  output:
    dir: "./saved_datasets"

