General:
      Measurement    : 
          - name : higgs_tautau_signal_strength_nosyst 
            systs : 
                -
                  
          - name  : higgs_tautau_signal_strength
            systs :
                  - JES
                  - TES
          
            
      #Measurement : higgs_tautau_signal_strength
      POI            : mu_htautau
#use_syst : False
Samples:
    - Name              : htautau
      Tree              : tree_htautau
      SamplePath        : /data/NSBI_tutorial_data/saved_datasets/dataset_nominal.root
      Weight            : weights
      UseAsReference    : True
      UseAsBasis        : True

    - Name              : ttbar
      Tree              : tree_ttbar
      SamplePath        : /data/NSBI_tutorial_data/saved_datasets/dataset_nominal.root
      Weight            : weights
      UseAsReference    : True
      UseAsBasis        : True
        
    - Name : ztautau
      Tree              : tree_ztautau
      SamplePath        : /data/NSBI_tutorial_data/saved_datasets/dataset_nominal.root
      Weight            : weights
      UseAsReference    : False
      UseAsBasis        : True

NormFactors:
  - Name: "mu_htautau"
    Samples: "htautau"
    Nominal: 1
    Bounds: [0, 10]
  - Name: "mu_ztautau"
    Samples: "ztautau"
    Nominal: 1
    Bounds: [0, 10]
  - Name: "mu_ttbar"
    Samples: "ttbar"
    Nominal: 1
    Bounds: [0, 10]
    
Systematics:
    -   Name                : JES
        Type                : NormPlusShape
        Nominal             : 0
        Samples             : 
              - htautau
              - ztautau
              - ttbar
        Up                  : 
            -   SampleName        : htautau
                Path              : /data/NSBI_tutorial_data/saved_datasets/dataset_JES_up.root
                Tree              : tree_htautau
                Weight            : weights
            -   SampleName        : ztautau
                Path              : /data/NSBI_tutorial_data/saved_datasets/dataset_JES_up.root
                Tree              : tree_ztautau
                Weight            : weights
            -   SampleName        : ttbar
                Path              : /data/NSBI_tutorial_data/saved_datasets/dataset_JES_up.root
                Tree              : tree_ttbar
                Weight            : weights
        Dn                  :
            -   SampleName        : htautau
                Path              : /data/NSBI_tutorial_data/saved_datasets/dataset_JES_dn.root
                Tree              : tree_htautau
                Weight            : weights
            -   SampleName        : ztautau
                Path              : /data/NSBI_tutorial_data/saved_datasets/dataset_JES_dn.root
                Tree              : tree_ztautau
                Weight            : weights
            -   SampleName        : ttbar
                Path              : /data/NSBI_tutorial_data/saved_datasets/dataset_JES_dn.root
                Tree              : tree_ttbar
                Weight            : weights
    -   Name                : TES
        Type                : NormPlusShape
        Nominal             : 0
        Samples             : 
              - htautau
              - ztautau
              - ttbar
        Up                  :
            -   SampleName        : htautau
                Path              : /data/NSBI_tutorial_data/saved_datasets/dataset_TES_up.root
                Tree              : tree_htautau
                Weight            : weights
            -   SampleName        : ztautau
                Path              : /data/NSBI_tutorial_data/saved_datasets/dataset_TES_up.root
                Tree              : tree_ztautau
                Weight            : weights
            -   SampleName        : ttbar
                Path              : /data/NSBI_tutorial_data/saved_datasets/dataset_TES_up.root
                Tree              : tree_ttbar
                Weight            : weights
        Dn                  :
            -   SampleName        : htautau
                Path              : /data/NSBI_tutorial_data/saved_datasets/dataset_TES_dn.root
                Tree              : tree_htautau
                Weight            : weights
            -   SampleName        : ztautau
                Path              : /data/NSBI_tutorial_data/saved_datasets/dataset_TES_dn.root
                Tree              : tree_ztautau
                Weight            : weights
            -   SampleName        : ttbar
                Path              : /data/NSBI_tutorial_data/saved_datasets/dataset_TES_dn.root
                Tree              : tree_ttbar
                Weight            : weights


TrainingFeatures:
    - DER_mass_transverse_met_lep
    - log_DER_mass_vis
    - log_DER_pt_h
    - DER_deltar_had_lep
    - log_DER_pt_tot
    - log_DER_sum_pt
    - DER_pt_ratio_lep_had
    - DER_met_phi_centrality
    
TrainingFeaturesToStandardize:
    - DER_mass_transverse_met_lep
    - log_DER_mass_vis
    - log_DER_pt_h
    - DER_deltar_had_lep
    - log_DER_pt_tot
    - log_DER_sum_pt
    - DER_pt_ratio_lep_had
    - DER_met_phi_centrality

Regions:
-   Name: CR
    Filter: presel_score<-1.0
    Variable: presel_score
    Type: binned
    Binning:
        - -8.747320175170898
        - -6.810490310192108
        - -4.873660445213318
        - -2.9368305802345276
        - -1.0000007152557373
-   Name: SR_binned
    Filter: presel_score>3.75
    Variable: presel_score
    Type: binned
    Binning:
        - 4.500021934509277
        - 5.942246437072754
-   Name            : SR
    Filter          : presel_score>=-1.0 & presel_score<=3.75
    Type            : unbinned
    Variable        : null
    Binning         : null
    AsimovWeights   : /data/NSBI_tutorial_data/saved_datasets/asimov_weights.npy
    TrainedModels:
        - SampleName    : htautau
          Nominal   : 
               Models  : /data/NSBI_tutorial_data/saved_datasets/output_training_nominal/output_model_params_htautau/
               Ratios  : /data/NSBI_tutorial_data/saved_datasets/output_training_nominal/output_ratios_htautau/ratio_htautau.npy
          Systematics    :
             - SystName: TES
               ModelsUp: /data/NSBI_tutorial_data/saved_datasets/output_training_systematics/output_model_params_htautau_TES_Up/
               ModelsDn: /data/NSBI_tutorial_data/saved_datasets/output_training_systematics/output_model_params_htautau_TES_Dn/
               RatiosUp: /data/NSBI_tutorial_data/saved_datasets/output_training_systematics/output_ratios_htautau_TES_Up/ratio_TES_Up.npy
               RatiosDn: /data/NSBI_tutorial_data/saved_datasets/output_training_systematics/output_ratios_htautau_TES_Dn/ratio_TES_Dn.npy
             - SystName: JES
               ModelsUp: /data/NSBI_tutorial_data/saved_datasets/output_training_systematics/output_model_params_htautau_JES_Up/
               ModelsDn: /data/NSBI_tutorial_data/saved_datasets/output_training_systematics/output_model_params_htautau_JES_Dn/
               RatiosUp: /data/NSBI_tutorial_data/saved_datasets/output_training_systematics/output_ratios_htautau_JES_Up/ratio_JES_Up.npy
               RatiosDn: /data/NSBI_tutorial_data/saved_datasets/output_training_systematics/output_ratios_htautau_JES_Dn/ratio_JES_Dn.npy
        - SampleName    : ttbar
          Nominal       : 
                Models  : /data/NSBI_tutorial_data/saved_datasets/output_training_nominal/output_model_params_ttbar/
                Ratios  : /data/NSBI_tutorial_data/saved_datasets/output_training_nominal/output_ratios_ttbar/ratio_ttbar.npy
          Systematics    :
            - SystName: TES
              ModelsUp: /data/NSBI_tutorial_data/saved_datasets/output_training_systematics/output_model_params_ttbar_TES_Up/
              ModelsDn: /data/NSBI_tutorial_data/saved_datasets/output_training_systematics/output_model_params_ttbar_TES_Dn/
              RatiosUp: /data/NSBI_tutorial_data/saved_datasets/output_training_systematics/output_ratios_ttbar_TES_Up/ratio_TES_Up.npy
              RatiosDn: /data/NSBI_tutorial_data/saved_datasets/output_training_systematics/output_ratios_ttbar_TES_Dn/ratio_TES_Dn.npy
            - SystName: JES
              ModelsUp: /data/NSBI_tutorial_data/saved_datasets/output_training_systematics/output_model_params_ttbar_JES_Up/
              ModelsDn: /data/NSBI_tutorial_data/saved_datasets/output_training_systematics/output_model_params_ttbar_JES_Dn/ 
              RatiosUp: /data/NSBI_tutorial_data/saved_datasets/output_training_systematics/output_ratios_ttbar_JES_Up/ratio_JES_Up.npy
              RatiosDn: /data/NSBI_tutorial_data/saved_datasets/output_training_systematics/output_ratios_ttbar_JES_Dn/ratio_JES_Dn.npy
        - SampleName    : ztautau
          Nominal       : 
                Models  : /data/NSBI_tutorial_data/saved_datasets/output_training_nominal/output_model_params_ztautau/
                Ratios  : /data/NSBI_tutorial_data/saved_datasets/output_training_nominal/output_ratios_ztautau/ratio_ztautau.npy
          Systematics    :
             - SystName: TES
               ModelsUp: saved_datasets/output_training_systematics/output_model_params_ztautau_TES_Up/
               ModelsDn: saved_datasets/output_training_systematics/output_model_params_ztautau_TES_Dn/
               RatiosUp: saved_datasets/output_training_systematics/output_ratios_ztautau_TES_Up/ratio_TES_Up.npy
               RatiosDn: saved_datasets/output_training_systematics/output_ratios_ztautau_TES_Dn/ratio_TES_Dn.npy
             - SystName: JES
               ModelsUp: saved_datasets/output_training_systematics/output_model_params_ztautau_JES_Up/
               ModelsDn: saved_datasets/output_training_systematics/output_model_params_ztautau_JES_Dn/
               RatiosUp: saved_datasets/output_training_systematics/output_ratios_ztautau_JES_Up/ratio_JES_Up.npy
               RatiosDn: saved_datasets/output_training_systematics/output_ratios_ztautau_JES_Dn/ratio_JES_Dn.npy
                           