universe = vanilla

executable = FAIR_universe_Higgs_tautau/htcondor/run_step.sh
arguments  = data_loader $(CONFIG)

log    = logs/data_loader.$(Cluster).log
output = logs/data_loader.$(Cluster).out
error  = logs/data_loader.$(Cluster).err

request_cpus   = $(CPUS:1)
request_memory = $(MEM:64GB)
request_gpus   = $(GPUS:0)
request_disk   = $(DISK:64GB)

stream_output = True
stream_error  = True

should_transfer_files = YES
when_to_transfer_output = ON_EXIT

transfer_input_files = pyproject.toml, src, FAIR_universe_Higgs_tautau, README.md
transfer_output_files = FAIR_universe_Higgs_tautau/data, FAIR_universe_Higgs_tautau/saved_datasets
transfer_output_remaps = "FAIR_universe_Higgs_tautau/data = ./FAIR_universe_Higgs_tautau/data, FAIR_universe_Higgs_tautau/saved_datasets = ./FAIR_universe_Higgs_tautau/saved_datasets"

+SingularityImage = "/staging/jsandesara/nsbi-env-gpu.sif"

queue
